#!/bin/sh
# Xcode equivalent of the Gradle flavor guard in android/app/build.gradle:
# refuses to build a scheme whose secrets are not the ones compiled into
# lib/core/env/env.g.dart.
set -eu

case "$CONFIGURATION" in
  *-dev)  FLAVOR=dev ;;
  *-prod) FLAVOR=prod ;;
  *)
    echo "warning: configuration '$CONFIGURATION' has no flavor suffix, skipping env check"
    exit 0
    ;;
esac

PROJECT_ROOT="$SRCROOT/.."
LOCK="$PROJECT_ROOT/.envied.lock"
ENV_FILE="$PROJECT_ROOT/.env.$FLAVOR"

if [ ! -f "$LOCK" ]; then
  echo "error: missing .envied.lock - env.g.dart was not generated by build.sh. Run: ./build.sh $FLAVOR"
  exit 1
fi

LOCKED_DIGEST=$(sed -n '1p' "$LOCK")
LOCKED_FLAVOR=$(sed -n '2p' "$LOCK")

if [ "$LOCKED_FLAVOR" != "$FLAVOR" ]; then
  echo "error: flavor mismatch - building '$FLAVOR' but env.g.dart holds '$LOCKED_FLAVOR' secrets. Run: ./build.sh $FLAVOR"
  exit 1
fi

if [ ! -f "$ENV_FILE" ]; then
  echo "error: missing .env.$FLAVOR"
  exit 1
fi

if command -v md5 >/dev/null 2>&1; then
  DIGEST=$(md5 -q "$ENV_FILE")
else
  DIGEST=$(md5sum "$ENV_FILE" | cut -d' ' -f1)
fi

if [ "$DIGEST" != "$LOCKED_DIGEST" ]; then
  echo "error: .env.$FLAVOR changed since env.g.dart was generated. Run: ./build.sh $FLAVOR"
  exit 1
fi

echo "env check ok: $FLAVOR"
