name: savepass
description: "App for store passwords or safe notes in a secure way"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  atomic_design_system:
    path: ../atomic_design_system
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cryptography: ^2.7.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  device_info_plus: ^10.1.0
  encrypt: ^5.0.3
  envied: ^0.5.4+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.3.2
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.14
  formz: ^0.7.0
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  intl: any
  local_auth: ^2.3.0
  logger: ^2.4.0
  lottie: ^3.1.2
  package_info_plus: ^8.1.1
  permission_handler: ^11.3.1
  skeletonizer: ^1.4.2
  supabase_flutter: ^2.8.0
  syncfusion_flutter_pdfviewer: ^27.1.51
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/images/auth/
    - assets/images/dashboard/
    - assets/images/card/
    - assets/lotties/
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Geist-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/Geist-Light.ttf
          weight: 300
        - asset: assets/fonts/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Geist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geist-Black.ttf
          weight: 800
        - asset: assets/fonts/Geist-UltraBlack.ttf
          weight: 900
  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/logo_light.png"
  remove_alpha_ios: true
